# Fuerza que /admin y config.yml no se sirvan desde caché
[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

# Accesos a Identity desde cualquier subdominio/dominio que uses
[[headers]]
  for = "/.netlify/identity/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-store"
