backend:
  name: git-gateway
  branch: main
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
publish_mode: simple
site_url: "https://grimlayertattoo.com"

locale: "en"
i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Featured Image", name: "cover", widget: "image", choose_url: false, required: true }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Headline (EN)", name: "headline_en", widget: "string" }
          - { label: "Headline (ES)", name: "headline_es", widget: "string" }
          - { label: "Intro (EN)", name: "intro_en", widget: "text" }
          - { label: "Intro (ES)", name: "intro_es", widget: "text" }
  - name: "bookings"
    label: "Booking Requests"
    folder: "content/booking"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Client name", name: "client", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone", name: "phone", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Reference images", name: "refs", widget: "list", summary: "{{fields.image}}", field: {label: "Image", name: "image", widget: "image"} }
      - { label: "Notes (private)", name: "notes", widget: "text", required: false }
