backend:
  name: git-gateway
  branch: main

# Evita problemas de caché en móvil
publish_mode: editorial_workflow
local_backend: false
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "https://grimlayertattoo.com"
display_url: "https://grimlayertattoo.com"
logo_url: "/assets/uploads/logo.png"

i18n:
  structure: multiple_files
  locales: [en, es]
  default_locale: en

collections:
  - name: "portfolio"
    label: "Portfolio"
    label_singular: "Piece"
    folder: "content/portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cover", name: "image", widget: "image", allow_multiple: false }
      - { label: "Description", name: "body", widget: "markdown", i18n: true }

  - name: "aftercare"
    label: "Aftercare"
    folder: "content/aftercare"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Content", name: "body", widget: "markdown", i18n: true }

  - name: "booking"
    label: "Booking Requests"
    folder: "content/booking"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Client name", name: "client", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Phone / WhatsApp", name: "phone", widget: "string", required: false }
      - { label: "Preferred date", name: "preferred_date", widget: "datetime", required: false }
      - { label: "Idea / description", name: "body", widget: "markdown" }
      - { label: "Reference images", name: "refs", widget: "list", collapsed: true, fields: [{label: "Image", name: "img", widget: "image"}] }
